FROM debian:stretch

# File Author / Maintainer
MAINTAINER Aida Ripoll Cladellas <aida.ripoll@crg.eu> 

RUN apt-get update

RUN apt-get install -y ncbi-blast+;

# Default location of BLAST databases
VOLUME /blastdb
ENV BLASTDB /blastdb

# Clean cache
RUN apt-get clean
RUN set -x; rm -rf /var/lib/apt/lists/*